### PR TITLE
Fix pyOCD/README link

### PR DESCRIPTION
**Pull request by carlosperate**
Tiny PR just to fix a link pointing to the wrong file extension.

### CODE REVIEW

**Comment by carlosperate** [comment]
@iriark01 friendly ping?

**Comment by iriark01** [comment]
Isn't everything moving away from mbedmicro anyway?

**Comment by carlosperate** [comment]
Don't know, but right now there is a broken link in https://docs.mbed.com/docs/debugging-on-mbed/en/latest/Debugging/pyOCD/

**Comment by iriark01** [comment]
@sg- has this page already been migrated?

**Comment by sg-** [comment]
Not that I know of.

**Pull request merged**
