### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AnotherButler**
Add new images for Debugging with Eclipse and pyOCD page

### CODE REVIEW

**Comment by janjongboom** [comment]
@iriark01 Can this be landed? Images are broken right now.

**Comment by iriark01** [comment]
I think the docs site only supports PNG

**Comment by janjongboom** [comment]
@AnotherButler Can we get these files in a format that more browsers than just Chrome supports?

**Comment by AnotherButler** [comment]
@janjongboom I've uploaded the files as pngs. Please let me know if they work.

**Comment by janjongboom** [comment]
@iriark01 ^ We do need to change the md files too, but other than that it looks good.

**Comment by iriark01** [comment]
Cool, I'll start an edit

**Pull request closed without merging**
